name: Backup Database
on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta diariamente a medianoche
  workflow_dispatch:     # Permite ejecutarlo manualmente cuando quieras

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Generate Backups
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          pg_dump "$DB_URL" --schema-only --section=pre-data --schema=public --no-privileges --no-owner > tablas_puras.sql
          pg_dump "$DB_URL" --data-only --schema=public --column-inserts --no-privileges --no-owner > datos.sql
          pg_dump "$DB_URL" --schema-only --section=post-data --schema=public --no-privileges --no-owner > constraints.sql

      - name: Push to Repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add *.sql
          # Solo hace commit y push si hubo cambios en los archivos
          git diff --quiet && git diff --staged --quiet || (git commit -m "Backup autom√°tico: $(date)" && git push)
