name: Backup Database
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get install -y wget gnupg2 lsb-release
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17
          
      - name: Generate Backups
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          # Crear la carpeta de destino si no existe
          mkdir -p backup
          
          PG_DUMP_PATH="/usr/lib/postgresql/17/bin/pg_dump"
          
          # Guardar los archivos directamente en la carpeta 'backup/'
          $PG_DUMP_PATH "$DB_URL" --schema-only --section=pre-data --schema=public --no-privileges --no-owner > backup/tablas_puras.sql
          $PG_DUMP_PATH "$DB_URL" --data-only --schema=public --column-inserts --no-privileges --no-owner > backup/datos.sql
          $PG_DUMP_PATH "$DB_URL" --schema-only --section=post-data --schema=public --no-privileges --no-owner > backup/constraints.sql
          
      - name: Push to Repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Asegurar que Git tome en cuenta los archivos dentro de la carpeta backup
          git add backup/*.sql
          
          # Commit y push (reemplazará los archivos anteriores si existen)
          git commit -m "Backup automático en carpeta: $(date)" || echo "No hay cambios para subir"
          git push
